[package]
name = "rust_math"
version = "0.1.0"
authors = ["anthony"]
edition = "2018"

[lib]
name = "rust_math"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rust_decimal = "1.26"
rust_decimal_macros = "1.26"
rayon = "1.5"
lazy_static = "1.4"